/* Auth */
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_REMOVE_TOKEN = 'AUTH_REMOVE_TOKEN';
export const AUTH_SIGNIN_ERROR = 'AUTH_SIGNIN_ERROR';
export const AUTH_LOGGING_IN = 'AUTH_LOGGING_IN';
export const AUTH_SIGNUP_ERROR = 'AUTH_SIGNUP_ERROR';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_REGISTERING = 'AUTH_REGISTERING';

/* Service */
export const GET_SERVICES = 'GET_SERVICES';
export const GETTING_SERVICES = 'GETTING_SERVICES';
export const SEARCH_SERVICE = 'SEARCH_SERVICE';
export const SEARCHING_SERVICE = 'SEARCHING_SERVICE';